<?php

namespace SchoolManagementSystem\Repository;

/**
 * RolesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolesRepository extends \Doctrine\ORM\EntityRepository
{
}
